### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by xlinxlin** [jordanlab/STing#5]
Hi!

I'm testing your tool but got an error message with your test command `db_util.py fetch --query "Neisseria spp." --out_dir my_dbs --build_index`. Here is my command and the output, can you help me for this? Thanks!

```
(base) mkzhouy1@supermicro:/mnt/data/2007-mlst-silke/STing_demo$ ~/git/STing/scripts/db_util.py fetch --query "Neisseria spp." --out_dir my_dbs --build_index
Database: "Neisseria spp."
 Fetching allele sequences: 
 - https://pubmlst.org/data/alleles/neisseria/abcZ.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/abcZ.fa
 - https://pubmlst.org/data/alleles/neisseria/adk.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/adk.fa
 - https://pubmlst.org/data/alleles/neisseria/aroE.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/aroE.fa
 - https://pubmlst.org/data/alleles/neisseria/fumC.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/fumC.fa
 - https://pubmlst.org/data/alleles/neisseria/gdh.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/gdh.fa
 - https://pubmlst.org/data/alleles/neisseria/pdhC.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/pdhC.fa
 - https://pubmlst.org/data/alleles/neisseria/pgm.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/pgm.fa
 Fetching profiles: 
 - https://pubmlst.org/data/profiles/neisseria.txt -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/profile.txt
Building STing index:
/home/mkzhouy1/git/STing/bin/indexer -c /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/config.txt -p /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/db/index
Traceback (most recent call last):
  File "/home/mkzhouy1/git/STing/scripts/db_util.py", line 271, in <module>
    main()
  File "/home/mkzhouy1/git/STing/scripts/db_util.py", line 267, in main
    args.func(dbFileContent, args, parser)
  File "/home/mkzhouy1/git/STing/scripts/db_util.py", line 197, in fetch
    build_index(configFileName, outPrefix)
  File "/home/mkzhouy1/git/STing/scripts/db_util.py", line 245, in build_index
    stderr=subprocess.STDOUT).decode("utf-8")
  File "/home/mkzhouy1/anaconda3/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/mkzhouy1/anaconda3/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/home/mkzhouy1/git/STing/bin/indexer -c /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/config.txt -p /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/db/index' returned non-zero exit status 1.
```

**Comment by ar0ch** [comment]
Ah, this is a bug in `db_util.py` that we didn't catch when making config paths relative.  Could you give the version of `db_util.py` I just pushed a try

**Comment by xlinxlin** [comment]
> Ah, this is a bug in `db_util.py` that we didn't catch when making config paths relative. Could you give the version of `db_util.py` I just pushed a try

The version number is 1.2
```
(base) mkzhouy1@supermicro:~$ ~/git/STing/scripts/db_util.py --version
db_util.py
  version:	1.2
  last update:	11/14/2019
```

**Comment by ar0ch** [comment]
I just didn't bump the version (just pushed that too)

**Comment by xlinxlin** [comment]
@ar0ch Now it works, thank you!
```
(base) mkzhouy1@supermicro:/mnt/data/2007-mlst-silke/STing_demo$ ~/git/STing/scripts/db_util.py fetch --query "Neisseria spp." --out_dir my_dbs --build_index
Database: "Neisseria spp."
 Fetching allele sequences: 
 - https://pubmlst.org/data/alleles/neisseria/abcZ.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/abcZ.fa
 - https://pubmlst.org/data/alleles/neisseria/adk.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/adk.fa
 - https://pubmlst.org/data/alleles/neisseria/aroE.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/aroE.fa
 - https://pubmlst.org/data/alleles/neisseria/fumC.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/fumC.fa
 - https://pubmlst.org/data/alleles/neisseria/gdh.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/gdh.fa
 - https://pubmlst.org/data/alleles/neisseria/pdhC.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/pdhC.fa
 - https://pubmlst.org/data/alleles/neisseria/pgm.tfa -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/pgm.fa
 Fetching profiles: 
 - https://pubmlst.org/data/profiles/neisseria.txt -> /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/profile.txt
Building STing index:
/home/mkzhouy1/git/STing/bin/indexer -c /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/config.txt -p /mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/db/index
Loading sequences from sequences files:

N	Loci	#Seqs.	File
1	abcZ	1077	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/abcZ.fa
2	adk	840	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/adk.fa
3	aroE	1118	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/aroE.fa
4	fumC	1184	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/fumC.fa
5	gdh	1156	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/gdh.fa
6	pdhC	1096	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/pdhC.fa
7	pgm	1172	/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/pgm.fa

Total sequences loaded: 7643

Loading the profiles file... Done!
Creating and saving ESA index from loaded sequences... Done!
Index created successfully with prefix '/mnt/data/2007-mlst-silke/STing_demo/my_dbs/neisseria_spp/db/index'
```

**Comment by ar0ch** [comment]
Great!  😄
